[package]
name = "handwritten-cluster"
version = "0.1.0"
edition = "2024"

[dependencies]
efficient_pca.workspace = true
dbscan = "0.3.1"
kneed = "1.0.0"
ndarray.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
