[package]
name = "handwritten-cluster"
version = "0.1.0"
edition = "2024"

[dependencies]
# dbscan = "0.3.1"
# kneed = "1.0.0"
ndarray.workspace = true
handwritten.workspace = true
rusqlite.workspace = true
image = "0.25.8"
clap.workspace = true