[package]
name = "handwritten-pca"
version = "0.1.0"
edition = "2024"

[dependencies]
efficient_pca = { version = "0.1.8", default-features = false, features = ["backend_faer"] }
ndarray.workspace = true
clap.workspace = true
rusqlite.workspace = true
serde_json = "1.0.145"
