[package]
name = "handwritten-viz"
version = "0.1.0"
edition = "2024"

[dependencies]
rerun = { version = "0.25.1", default-features = false, features = ["sdk"] }
clap.workspace = true
rusqlite.workspace = true