[package]
name = "handwritten-heatmap"
version = "0.1.0"
edition = "2024"

[dependencies]
image.workspace = true
ndarray.workspace = true
handwritten.workspace = true
clap.workspace = true
# rusqlite.workspace = true
rayon.workspace = true
